### PR TITLE
Add flight path preview when selecting images

### PR DESCRIPTION
**Pull request by pierotofy**
Adds a plot of the flight path of the selected images (when GPS information is available). This is useful because it provides a sanity check on the selected images.

TODO:
 * Handle multiple image selects / drops
 * Add ability to specify a crop boundary directly from the map, instead of the tedious process of using geojson.io to specify a crop boundary via the task options.
 * (optional) I'm not sure I'm committed to do this right away, but could be neat to have the ability to remove images interactively, to remove mistakenly selected images.
 * Gracefully handle dataset with no georeferencing
 * Test very large datasets (e.g. more than 5000 images), exifr promises a ~2 seconds processing time, but I would test to see if it crashes...

### CODE REVIEW

**Comment by pierotofy** [comment]
image

**Comment by pierotofy** [comment]
Closes #1017

**Comment by Saijin-Naib** [comment]
Love it! 

Is a tabular list also possible alongside the map?

**Comment by pierotofy** [comment]
What would be the use case?

**Comment by Saijin-Naib** [comment]
An easier (potentially) way to verify image geolocation and status, especially with mixed geoloc and non-geoloc data, without map view encompassing half the globe or worse to fit the preview extent. 

Also, thinking forward, might work for manual fixes/overrides to write out as geo.txt direct from this QA/QC step

**Comment by pierotofy** [comment]
I could add buttons to export the data to GeoJSON / CSV. Could that work?

**Comment by Saijin-Naib** [comment]
I think that covers some other excellent use-cases and simplifies other needed tools in the toolbox, so that is really cool for sure!

**Comment by pierotofy** [comment]
Final implementation: 
image

**Pull request merged**
