### PR TITLE
add: new vegetation index

### PR DESCRIPTION
**Pull request by NtskwK**
- Structure-Insensitive Pigment Index
- Modified Normalized Difference Vegetation Index.
- Ratio Enhanced Normalized Difference Vegetation Index.
- Modified Transformed Vegetation Index 1.
- Modified Transformed Vegetation Index 2.
- Greenness Index.
- Transparency Vegetation Index.
- Modified Chlorophyll Absorption Reflectance Index 1.
- Chlorophyll Index.
- Simple Ratio.
- Modified Simple Ratio 2.
- Improved Perpendicular Vegetation Index.

by @NtskwK , @QinShengLiangAn

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
Oooh, these look great!

Do you have a source for them so we can learn about appropriate usage?

**Comment by NtskwK** [comment]
Yeh, I'll show you a list of papers.
Our group use them for some researchs about agriculture.

- Assessment of photosynthetic radiation-use efficiency with spectral reflectance (1995)

- Relationships between leaf pigment content and spectral reflectance acrossa wide range of species, leaf structures and developmental stages (2002)

- Quantitative estimation of chlorophyll-a using reflectance spectra: Experiments with autumn chestnut and maple leaves (1994)

- Hyperspectral vegetation indices and novel algorithms for predicting green LAI of crop canopies: Modeling and validation in the context of precision agriculture (2004)

- Business literacy and development: Evidence from a randomized controlled trial in rural Mexico (2013)

- Comparing prediction power and stability of broadband and hyperspectral vegetation indices for estimation of green leaf area index and canopy chlorophyll density (2001)

- Hyperspectral vegetation indices and novel algorithms for predicting green LAI of crop canopies: Modeling and validation in the context of precision agriculture (2004)

- Remote estimation of canopy chlorophyll content in crops (2005)

- Derivation of leaf‐area index from quality of light on the forest floor (1969)

- Calculating the vegetation index faster (1990)

**Review by Saijin-Naib — COMMENTED** [review]
Looks great to me!

**Comment by pierotofy** [comment]
Thanks @NtskwK :+1: next to the help for each index, could you add descriptions of what the index is useful for (without needing to read a research paper)? See the other indexes for an example of descriptions :pray:

**Pull request closed without merging**
