### PR TITLE
Imperial units support, improvements, fixes, plugins API expansion

### PR DESCRIPTION
**Pull request by pierotofy**
Various improvements and fixes.

### CODE REVIEW

**Comment by pierotofy** [comment]
Well, I started adding support for imperial units (both international and US), because it's overdue.

**Comment by pierotofy** [comment]
#1065

**Comment by smathermather** [comment]
[The Mars Climate Orbiter](https://en.wikipedia.org/wiki/Mars_Climate_Orbiter) will thank you.

**Comment by pierotofy** [comment]
Also ~25% speed-up in rendering DSM/DTM tiles.

**Comment by pierotofy** [comment]
This should be good to go.

**Comment by smathermather** [comment]
Is it too late to ask for a couple more imperial units, specifically the following length and area measures?:

Area: gallons per fathom (GPF)

Length: hogsheads per rood (HPR)

ht @ivangayton

**Comment by pierotofy** [comment]
Shouldn't be a problem, one can just modify `Units.js` and `UnitSelector.jsx`. 

https://www.youtube.com/watch?v=d9t5LqHcboI

**Comment by smathermather** [comment]
> Shouldn't be a problem, one can just modify `Units.js` and `UnitSelector.jsx`. 

Super tempted to do that on crankyserver...

**Pull request merged**
