### PR TITLE
Replaced most glyphicons with fa icons

### PR DESCRIPTION
**Pull request by Mingos1**
I finished up replacing all of the inline icons. I left all mentions of glyphicons in the stylesheets as is (in case you wanted to revert back to glyphs) and left 1 glyphicon component in (shown below) since I couldn't find a FA equivalent.

### CODE REVIEW

**Comment by Mingos1** [comment]
#745

**Comment by pierotofy** [comment]
Hey @Mingos1 :hand: thanks for the PR!

I noticed that some icons are not loading, while others are "squished" against the labels of buttons.

image

Could you also make sure to turn off your text editor's auto-format option? It makes it really difficult to see what you changed :pray: 

Feel free to open a new PR or edit the current one.

**Comment by Mingos1** [comment]
Oh no, this is definitely an oversight on my part. Thank you for catching it and letting me know!

I am going to go back and try to find anymore with the same issues.

**Comment by Mingos1** [comment]
After trying it a few times, I can't recreate the UI issues on my system (Win10, Mozilla Firefox and Edge). In fact, my Docker image of ODM looks like this:

current_odm

Also, I currently do not have access to GCP files to help further test the UI changes.

**Comment by pierotofy** [comment]
You need to start the software with `./webodm.sh restart --dev`. You should see a "Developer Tools" tab on the left side. Make sure you have the latest version too via `./webodm.sh update`.

**Comment by Mingos1** [comment]
I redid a clone of the repo since my original clone was missing the `-config core.autocrlf=input` flag, preventing me from running `./webodm.sh restart --dev`. 

I'll get right to fixing the icons and visual issues and come back if I come across any issues.

**Comment by pierotofy** [comment]
I'll close this for now; feel free to re-open it once it's ready/done, or to open a new PR. :+1:

**Pull request closed without merging**
