### PR TITLE
Improved performance of camera shot markers 

### PR DESCRIPTION
**Pull request by zaakzaku**
I've processed around 1000 images. I wanted to show camera shot images but the browser struggle in rendering thousands of markers. 
struggle

### CODE REVIEW

**Comment by pierotofy** [comment]
Hey @zaakzaku :hand: thanks for the PR! Looks great. :pray:

**Comment by Saijin-Naib** [comment]
This is really neat! Can you describe what you changed and why it helps so I can understand better?

Is it not drawing all the markers all the time, but instead culling them so it only draws the visible ones?

**Comment by zaakzaku** [comment]
> This is really neat! Can you describe what you changed and why it helps so I can understand better?
> 
> Is it not drawing all the markers all the time, but instead culling them so it only draws the visible ones?

Thank you for your question,

The performance issue is due to the fact that each marker is an individual DOM element. Browsers struggle in rendering thousands of them.
In this case, an easy workaround would be instead to use Circle Markers and have them rendered on a Canvas.
`
 new L.CircleMarker(latlng, {
       color: '#3498db',
       fillColor: '#3498db',
       fillOpacity: 0.9,
       radius: 10,
       weight: 1
       });
`
With this solution, each Circle Marker is no longer an individual DOM element but instead is drawn by Leaflet onto a single Canvas, which is much easier to handle for the browser.

**Comment by Saijin-Naib** [comment]
That's really neat, and an elegant solution!

**Pull request merged**
