### PR TITLE
feat: hide button for unauthorized

### PR DESCRIPTION
**Pull request by NtskwK**
#1318

### CODE REVIEW

**Comment by pierotofy** [comment]
Did you test this?

**Comment by NtskwK** [comment]
Sorry, my problem. This is a very basic mistake.

**Comment by NtskwK** [comment]
@pierotofy Turn to #1555 , Please. Thank you very much.

**Comment by pierotofy** [comment]
I'm confused, but this is still broken unfortunately.

@NtskwK I appreciate the help for the fixes you've been doing, but always, always test *before* opening a pull request. It's a lot of work for maintainers to review pull requests. Opening one and then asking for how to achieve a desired result is not the way to go.

If you have questions about development, we have a channel here: https://community.opendronemap.org/c/developers-chat/21

I'll close this for now, feel free to re-open once it's been tested and works? :pray:

**Pull request closed without merging**
