### PR TITLE
Plant Health, Cloud Optimized GeoTIFFs and more

### PR DESCRIPTION
**Pull request by pierotofy**
image

This PR addresses multiple new features in WebODM, including:
 * Display Cloud-Optimized GeoTIFFS on the fly instead of static tiling
 * NDVI/VARI and countless other vegetation index displays
 * Histogram visualization and sliders
 * Colormaps (?)
 * UI fixes
 * New icons (font awesome 5)

Not ready, but getting close!

### CODE REVIEW

**Comment by pierotofy** [comment]
Dynamic hillshading! 
image

**Comment by philipperemy** [comment]
Thanks a lot for this pull request. Do you have a tutorial/howto about:

- NDVI/VARI and countless other vegetation index displays

It would be very helpful. Thanks a lot in advance :)

**Comment by chos-aeronautics** [comment]
Hi, I am excited about contributing with the community. I am now using webODM for getting FULL hd maps from my Sentera Sensor.

Is this PR  still in development ? or already working?  I am specially interested in  this:

 "NDVI/VARI and countless other vegetation index displays"

OR is there any case where i can find how they see NDVI index?

Regards!

**Comment by smathermather** [comment]
@chos-aeronautics, it's merged and already available in WebODM!

**Pull request merged**
