### PR TITLE
Fix histogram deformations

### PR DESCRIPTION
**Pull request by pierotofy**
Fixes https://community.opendronemap.org/t/possible-bug-weird-histograms-for-orthophoto/3248

### CODE REVIEW

**Comment by pierotofy** [comment]
image

**Comment by pierotofy** [comment]
cc @smathermather

**Comment by pierotofy** [comment]
Also better hillshade blending and fixed #770

**Comment by dmbworld** [comment]
Here is a comparison of the OLD with the NEW:
OLD:
SM_Old

NEW:
SM_New

There is a difference in elevation delineation and there are still some lines/blocks visible in the New version.

**Comment by pierotofy** [comment]
You can change the delineation by changing the `Shading` option to `Extruded`.

Can you annotate and/or zoom the lines/blocks you are seeing? Perhaps these are just hidden by the stronger shading in the previous version and are inherent to the data.

**Comment by dmbworld** [comment]
The settings were Jet/Extruded:
SM_New_Jet_Extruded-2

And the Old one zoomed in:
SM_Old-2


Hope this helps.

**Comment by smathermather** [comment]
Looks great!

**Comment by dmbworld** [comment]
@pierotofy do you require any more details to help resolve the block/line visibilty feature.

**Comment by pierotofy** [comment]
Did #771 fix it?

**Comment by dmbworld** [comment]
Sorry @pierotofy, missed that update, only seen #771 just now, updated and this is the result:
SM_New_Jet_Extruded-3

Unfortunately the lines/blocks have become more distinct.

**Comment by dmbworld** [comment]
@pierotofy Update: Unfortunately volume calculation is now broken. "Volume: computing... "and the cog is rotating with no value returned.
One of the CPUs rockets up to 100%.

**Comment by dmbworld** [comment]
@pierotofy I've spotted #773, does this actually deal with the issue I've described concerning volume calculation speed?

**Comment by dmbworld** [comment]
@pierotofy Thanks! #773 solves my mutterings above concerning volume calculation speeds.

**Comment by dmbworld** [comment]
I took a different approach to identifying the reason for the visible blocks. Using the same dataset from April this year and the most current release of OpenDroneMapper and the default settings in both cases. Two tasks were created. One Task used Fullsize images and the other Resized. Viewing in the same system the results were:
FULL SIZE:
SM_Fullsize

RESIZED:
SM_Resized

The blocks are clearly visible in the resized version and this is not the case in earlier ODM versions where I always Resized.

**Pull request merged**
