### PR TITLE
Remove ignore-gsd from pre-sets

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Comment by smathermather** [comment]
@Saijin-Naib -- that's officially the largest number of emoji responses I've gotten to a single pull request.

**Comment by Saijin-Naib** [comment]
> @Saijin-Naib -- that's officially the largest number of emoji responses I've gotten to a single pull request.

A lot of emotions, here. I feel like ```--ignore-gsd``` is at the root of like, 95% of our failure to process issues and I just really want to send it off proper.

**Comment by smathermather** [comment]
> A lot of emotions, here. I feel like `--ignore-gsd` is at the root of like, 95% of our failure to process issues and I just really want to send it off proper.

Yup. And you are fielding most of them.

**Comment by pierotofy** [comment]
Looks good, thanks!

**Pull request merged**
