### PR TITLE
Added chmod +x command to docker

### PR DESCRIPTION
**Pull request by pierotofy**
Fixes error

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
I ran `docker-compose build` then `docker-compose up`: 

```

 optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
 ---> 2e5a90147816
Removing intermediate container c7d95dcac47a
Step 17 : WORKDIR /webodm
 ---> Running in 20003845bdeb
 ---> b022bab52975
Removing intermediate container 20003845bdeb
Step 18 : RUN chmod +x *.sh
 ---> Running in 98a4c44fafef
 ---> 1a2ebf239fa1
Removing intermediate container 98a4c44fafef
Successfully built 1a2ebf239fa1
dmb2@OpenDroneMap:~/WebODM$ docker-compose up
Starting db
Recreating webapp
Attaching to db, webapp
db        | LOG:  database system was shut down at 2016-09-27 17:48:16 UTC
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
db        | LOG:  MultiXact member wraparound protections are now enabled
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
db        | LOG:  database system is ready to accept connections
db        | LOG:  autovacuum launcher started
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp exited with code 126
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp exited with code 126
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp exited with code 126
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
webapp    | /webodm/wait-for-it.sh: line 158: /webodm/start.sh: Permission denied
webapp    | /webodm/wait-for-it.sh: line 158: exec: /webodm/start.sh: cannot execute: Permission denied
^CGracefully stopping... (press Ctrl+C again to force)
Stopping webapp ... done
Stopping db ... done
dmb2@OpenDroneMap:~/WebODM$
```

**Comment by dakotabenjamin** [comment]
Trying again with --no-cache

**Comment by pierotofy** [comment]
Mm. I can't seem to be able to reproduce this on my Windows machine. What happens if you change `docker-compose.yml` at line 11 from:

```
    entrypoint: /bin/bash /webodm/wait-for-it.sh db:5432 -- /webodm/start.sh
```

to

```
    entrypoint: /bin/bash /webodm/wait-for-it.sh db:5432 -- /bin/bash /webodm/start.sh
```
?

**Comment by dakotabenjamin** [comment]
Currently cleaning my docker images/containers, I'll try that next.

**Comment by dakotabenjamin** [comment]
OK I changed that line, here's what I get:

```
dmb2@OpenDroneMap:~/WebODM$ docker-compose up
Starting db
Recreating webapp
Attaching to db, webapp
db        | LOG:  database system was shut down at 2016-09-27 19:48:47 UTC
webapp    | timeout: failed to run command ‘/webodm/wait-for-it.sh’: Permission denied
webapp    | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
db        | LOG:  MultiXact member wraparound protections are now enabled
db        | LOG:  database system is ready to accept connections
db        | LOG:  autovacuum launcher started
webapp    | Performing system checks...
webapp    |
webapp    | System check identified no issues (0 silenced).
webapp    |
webapp    | You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, app, auth, contenttypes, nodeodm, sessions.
webapp    | Run 'python manage.py migrate' to apply them.
webapp    | September 27, 2016 - 19:49:20
webapp    | Django version 1.10, using settings 'webodm.settings'
webapp    | Starting development server at http://0.0.0.0:8000/
webapp    | Quit the server with CONTROL-C.
```

**Comment by dakotabenjamin** [comment]
So I went in and did a manual migrate and it works fine, except I can't login using admin:admin

**Comment by dakotabenjamin** [comment]
I forgot: I changed the Dockerfile:
```
RUN chmod +x /webodm/*.sh
```

**Comment by pierotofy** [comment]
Yup, if you look at `start.sh` there's these lines:

```bash
echo Creating default superuser...
    echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python manage.py shell
```

Which initialize the default user. You can also run:

```bash
python manage.py createsuperuser
```

And follow the prompt to create a super admin account.

**Comment by pierotofy** [comment]
Did changing the Dockerfile with `RUN chmod +x /webodm/*.sh` make wait-for-it.sh work?

**Comment by dakotabenjamin** [comment]
No, it didn't, oddly enough. I think that line may be ineffective.

**Comment by pierotofy** [comment]
I'll look further into this.

**Comment by pierotofy** [comment]
I was able to reproduce the error on a Ubuntu 14.04 system. It's something about the permissions not being set when the container is initialized. Not sure what the root cause is, but I found a working fix for it.

Please see if it works now on your system with the latest commit, then when you are ready feel free to merge it or add more comments to the issue if the problem persists.

**Comment by dakotabenjamin** [comment]
Appears to be working fine :+1:

**Pull request merged**
