### PR TITLE
added shapefile & geojson temporary layer support

### PR DESCRIPTION
**Pull request by saricicekibrahim**
This may solve this issue;
https://github.com/OpenDroneMap/WebODM/issues/533

Adds a layer by drag & dropping a zipped shapefile or geojson on the map.
Layer appears just on recent session, disappears with refresh.
Layer fields can be seen by clicking objects.

Used shpjs, spin & react-dropzone.
Drag & drop works. An upload button may be added.
Only one file is supported.
Only zipped shapefile or geojson supported.
Can be tested with zip & geosjon files;
https://github.com/saricicekibrahim/postgis-training/tree/master/data
File should be less than 10 mb.

### CODE REVIEW

**Comment by pierotofy** [comment]
This is awesome @saricicekibrahim ! :+1: 

Only one minor request, if you have time, would it be possible to replace `dropzone-react` with `dropzone`? The main reason is that we already use the plain `dropzone` library in another part of the application and that would mean having two versions of a pretty heavy library included in the final bundle.

https://github.com/OpenDroneMap/WebODM/blob/master/app/static/app/js/components/ProjectListItem.jsx#L10

Otherwise I'll just merge it as-is and create a TODO for the future.

**Comment by saricicekibrahim** [comment]
sure. will work on dropzone..

**Comment by pierotofy** [comment]
Is it ready to be tested @saricicekibrahim ? I'd love to merge in time for the next release.

**Comment by saricicekibrahim** [comment]
no not yet i have to test for one more day

**Comment by saricicekibrahim** [comment]
no not yet i have to test for one more day

**Comment by saricicekibrahim** [comment]
It's ok i think.
with last changes;

Adds a layer by drag & dropping a zipped shapefile or geojson on the map.
Layer appears just on recent session, disappears with refresh.
Layer fields can be seen by clicking objects.

Used shpjs, spin & Dropzone.
For now drag & drop works, an upload button may be added.
Multiple files are supported.
Zipped shapefile(s) or geojson supported.
Can be tested with zip & geosjon files;
https://github.com/saricicekibrahim/postgis-training/tree/master/data
File should be less than 5 mb.

**Comment by pierotofy** [comment]
Thanks @saricicekibrahim ! I will test this sometimes tomorrow. Happy new year! :clinking_glasses:

**Pull request merged**
