### PR TITLE
Plugins Support

### PR DESCRIPTION
**Pull request by pierotofy**
Do not merge, I'm opening this PR early so that people can chime-in/provide feedback early on.

Relevant discussions: #92 #132 #53 http://community.opendronemap.org/t/openaerialmap-integration-into-webodm/61/7

### CODE REVIEW

**Comment by pierotofy** [comment]
Here's how to add a measurement control to the Leaflet map:

```javascript
PluginsAPI.Map.willAddControls([
		'measure/leaflet-measure.css',
		'measure/leaflet-measure.min.js'
	], function(options){
    L.control.measure({
      primaryLengthUnit: 'meters',
      secondaryLengthUnit: 'feet',
      primaryAreaUnit: 'sqmeters',
      secondaryAreaUnit: 'acres'
    }).addTo(options.map);
});
```

This is all done in the browser at runtime, dependencies get pulled in only after the appropriate event is raised.

**Comment by pierotofy** [comment]
Goodbye threaded scheduler, hello Celery. This allows people to load workers on separate machines for better background processing, tiling, plugin code execution (GRASS scripts anyone?)

Added `SharedTestWatch` class for monitoring execution in background workers via Redis implementation for unit testing.

**Comment by smathermather** [comment]
Woah -- so could tie in the blender scripts too with this, eh... ?

**Comment by pierotofy** [comment]
Absolutely!

**Comment by pierotofy** [comment]
posm-gcpi integration: 

image

**Pull request merged**
