### PR TITLE
Downgrade to GRASS 7.6

### LINKED ISSUE #732: Volume calculation returns Invalid response: [object Object]
### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 76 on Windows 10

### What is the problem?

I am unable to obtain volume measurement, I keep getting the following error: Invalid response: [object Object]

No error appeared on the console, and I could not find any log files.

In the web console, the returned object is: {"error":""}

Capture

### What should be the expected behavior?

One of the two:
- volume of the selected area
- clear error message

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I have tried processing the images with both profiles: Volume measurement, High Resolution. I then selected the area for which I would like to calculate the volume.

Capture_1

### PR DESCRIPTION
**Pull request by pierotofy**
Fixes #732 

GRASS 7.8 broke (or fixed) something, but the output from `r.volume` is not showing in the output.

7.8 output:

```
Starting GRASS GIS...
Creating new GRASS GIS location <location8>...
Cleaning up temporary files...
Executing <sh script.sh> ...
-PROJ_INFO-------------------------------------------------
name       : WGS 84 / UTM zone 15N
datum      : wgs84
ellps      : wgs84
proj       : utm
zone       : 15
no_defs    : defined
-PROJ_EPSG-------------------------------------------------
epsg       : 32615
-PROJ_UNITS------------------------------------------------
unit       : meter
units      : meters
meters     : 1
WARNING: Projection of dataset does not appear to match current location.

         Location PROJ_INFO is:
         name: WGS 84 / UTM zone 15N
         datum: wgs84
         ellps: wgs84
         proj: utm
         zone: 15
         no_defs: defined
         init: EPSG:32615

         Dataset PROJ_INFO is:
         name: WGS 84
         datum: wgs84
         ellps: wgs84
         proj: ll
         no_defs: defined

         ERROR: proj
Importing
</webodm/app/media/tmp/tmprtso3rpx_grass_engine/area_file.geojson> ...
Check if OGR layer <area_file> contains polygons...
 100%
Creating attribute table for layer <area_file>...
Default driver / database set to:
driver: sqlite
database: $GISDBASE/$LOCATION_NAME/$MAPSET/sqlite/sqlite.db
Importing 1 features (OGR layer <area_file>)...
 100%
-----------------------------------------------------
Registering primitives...
-----------------------------------------------------
Cleaning polygons
-----------------------------------------------------
Breaking polygons...
Breaking polygons (pass 1: select break points)...
 100%
Breaking polygons (pass 2: break at selected points)...
 100%
-----------------------------------------------------
Removing duplicates...
 100%
-----------------------------------------------------
Breaking boundaries...
 100%
-----------------------------------------------------
Removing duplicates...
 100%
-----------------------------------------------------
Cleaning boundaries at nodes...
 100%
-----------------------------------------------------
Merging boundaries...
 100%
-----------------------------------------------------
Removing dangles...
 100%
-----------------------------------------------------
Building areas...
 100%
-----------------------------------------------------
Removing bridges...
 100%
-----------------------------------------------------
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
-----------------------------------------------------
Finding centroids for OGR layer <area_file>...
 100%
-----------------------------------------------------
Writing centroids...
 100%
-----------------------------------------------------
1 input polygons
Total area: 5.82563 (1 areas)
-----------------------------------------------------
Copying features...
 100%
Building topology for vector map <polygon_area@PERMANENT>...
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
Attaching centroids...
 100%
Reprojecting <polygon_area>...
Reprojecting primitives ...
Building topology for vector map <polygon_area@PERMANENT>...
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
Attaching centroids...
 100%
WARNING: Projection of dataset does not appear to match current location.

         Location PROJ_INFO is:
         name: WGS 84 / UTM zone 15N
         datum: wgs84
         ellps: wgs84
         proj: utm
         zone: 15
         no_defs: defined
         init: EPSG:32615

         Dataset PROJ_INFO is:
         name: WGS 84
         datum: wgs84
         ellps: wgs84
         proj: ll
         no_defs: defined

         ERROR: proj
Importing
</webodm/app/media/tmp/tmprtso3rpx_grass_engine/points_file.geojson> ...
Check if OGR layer <points_file> contains polygons...
 100%
Creating attribute table for layer <points_file>...
Default driver / database set to:
driver: sqlite
database: $GISDBASE/$LOCATION_NAME/$MAPSET/sqlite/sqlite.db
Importing 4 features (OGR layer <points_file>)...
 100%
-----------------------------------------------------
Building topology for vector map <polygon_points@PERMANENT>...
Registering primitives...
Reprojecting <polygon_points>...
Reprojecting primitives ...
Building topology for vector map <polygon_points@PERMANENT>...
Registering primitives...
WARNING: Option 'minordistance' is not available with GEOS buffering
Buffering areas...
 100%
Cleaning buffers...
Building parts of topology...
Building topology for vector map <region@PERMANENT>...
Registering primitives...
Snapping boundaries...
Reading features...
Snap vertices Pass 1: select points
 100%
Snap vertices Pass 2: assign anchor vertices
 100%
Snap vertices Pass 3: snap to assigned points
 100%
Breaking polygons...
Breaking polygons (pass 1: select break points)...
 100%
Breaking polygons (pass 2: break at selected points)...
 100%
Removing duplicates...
 100%
Breaking boundaries...
 100%
Removing duplicates...
 100%
Cleaning boundaries at nodes
 100%
Building topology for vector map <region@PERMANENT>...
Building areas...
 100%
Removing dangles...
 100%
Removing bridges...
 100%
Attaching islands...
Building topology for vector map <region@PERMANENT>...
Attaching islands...
 100%
Calculating centroids for all areas...
 100%
Generating list of boundaries to be deleted...
 100%
Deleting boundaries...
 100%
Calculating centroids for areas...
 100%
Building topology for vector map <region@PERMANENT>...
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
Attaching centroids...
 100%
Reading band 1 of 1...
Link to raster map <dsm> created.
Reading areas...
 100%
Writing raster map...
 100%
All subsequent raster operations will be limited to the MASK area. Removing
or renaming raster map named 'MASK' will restore raster operations to
normal.
Column <height> not found in the table <polygon_points>. Creating...
Reading features from vector map...
Update vector attributes...
 100%
v.what.rast complete. 4 records updated.
Reading features from vector map ...
WARNING: Strip exists with insufficient data
Ignoring 1 points (too dense)
WARNING: 3 points given for interpolation (after thinning) is less than
         given NPMIN=300
WARNING: There are less than 600 points for interpolation. No segmentation
         is necessary, to run the program faster set segmax=600 (see
         manual)
Processing all selected output files will require
145.71 KB of disk space for temp files.
Bitmap mask created
Processing segments in parallel...
Starting parallel work
 100%
v.surf.rst complete.
 100%
No clump map given, using MASK
 100%
Execution of <sh script.sh> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
```

7.6 output:

```
Starting GRASS GIS...
Creating new GRASS GIS location <location5>...
Executing <sh script.sh> ...
-PROJ_INFO-------------------------------------------------
name       : WGS 84 / UTM zone 15N
datum      : wgs84
ellps      : wgs84
proj       : utm
zone       : 15
no_defs    : defined
-PROJ_EPSG-------------------------------------------------
epsg       : 32615
-PROJ_UNITS------------------------------------------------
unit       : meter
units      : meters
meters     : 1
WARNING: Projection of dataset does not appear to match current location.

         Location PROJ_INFO is:
         name: WGS 84 / UTM zone 15N
         datum: wgs84
         ellps: wgs84
         proj: utm
         zone: 15
         no_defs: defined

         Dataset PROJ_INFO is:
         name: WGS 84
         datum: wgs84
         ellps: wgs84
         proj: ll
         no_defs: defined

         ERROR: proj
Importing
</webodm/app/media/tmp/tmprtso3rpx_grass_engine/area_file.geojson> ...
Check if OGR layer <area_file> contains polygons...
 100%
Creating attribute table for layer <area_file>...
Default driver / database set to:
driver: sqlite
database: $GISDBASE/$LOCATION_NAME/$MAPSET/sqlite/sqlite.db
Importing 1 features (OGR layer <area_file>)...
 100%
-----------------------------------------------------
Registering primitives...
-----------------------------------------------------
Cleaning polygons
-----------------------------------------------------
Breaking polygons...
Breaking polygons (pass 1: select break points)...
 100%
Breaking polygons (pass 2: break at selected points)...
 100%
-----------------------------------------------------
Removing duplicates...
 100%
-----------------------------------------------------
Breaking boundaries...
 100%
-----------------------------------------------------
Removing duplicates...
 100%
-----------------------------------------------------
Cleaning boundaries at nodes...
 100%
-----------------------------------------------------
Merging boundaries...
 100%
-----------------------------------------------------
Removing dangles...
 100%
-----------------------------------------------------
Building areas...
 100%
-----------------------------------------------------
Removing bridges...
 100%
-----------------------------------------------------
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
-----------------------------------------------------
Finding centroids for OGR layer <area_file>...
 100%
-----------------------------------------------------
Writing centroids...
 100%
-----------------------------------------------------
1 input polygons
Total area: 5.82563 (1 areas)
-----------------------------------------------------
Copying features...
 100%
Building topology for vector map <polygon_area@PERMANENT>...
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
Attaching centroids...
 100%
Reprojecting <polygon_area>...
Reprojecting primitives ...
Building topology for vector map <polygon_area@PERMANENT>...
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
Attaching centroids...
 100%
WARNING: Projection of dataset does not appear to match current location.

         Location PROJ_INFO is:
         name: WGS 84 / UTM zone 15N
         datum: wgs84
         ellps: wgs84
         proj: utm
         zone: 15
         no_defs: defined

         Dataset PROJ_INFO is:
         name: WGS 84
         datum: wgs84
         ellps: wgs84
         proj: ll
         no_defs: defined

         ERROR: proj
Importing
</webodm/app/media/tmp/tmprtso3rpx_grass_engine/points_file.geojson> ...
Check if OGR layer <points_file> contains polygons...
 100%
Creating attribute table for layer <points_file>...
Default driver / database set to:
driver: sqlite
database: $GISDBASE/$LOCATION_NAME/$MAPSET/sqlite/sqlite.db
Importing 4 features (OGR layer <points_file>)...
 100%
-----------------------------------------------------
Building topology for vector map <polygon_points@PERMANENT>...
Registering primitives...
Reprojecting <polygon_points>...
Reprojecting primitives ...
Building topology for vector map <polygon_points@PERMANENT>...
Registering primitives...
WARNING: Option 'minordistance' is not available with GEOS buffering
Buffering areas...
 100%
Cleaning buffers...
Building parts of topology...
Building topology for vector map <region@PERMANENT>...
Registering primitives...
Snapping boundaries...
Reading features...
Snap vertices Pass 1: select points
 100%
Snap vertices Pass 2: assign anchor vertices
 100%
Snap vertices Pass 3: snap to assigned points
 100%
Breaking polygons...
Breaking polygons (pass 1: select break points)...
 100%
Breaking polygons (pass 2: break at selected points)...
 100%
Removing duplicates...
 100%
Breaking boundaries...
 100%
Removing duplicates...
 100%
Cleaning boundaries at nodes
 100%
Building topology for vector map <region@PERMANENT>...
Building areas...
 100%
Removing dangles...
 100%
Removing bridges...
 100%
Attaching islands...
Building topology for vector map <region@PERMANENT>...
Attaching islands...
 100%
Calculating centroids for all areas...
 100%
Generating list of boundaries to be deleted...
 100%
Deleting boundaries...
 100%
Calculating centroids for areas...
 100%
Building topology for vector map <region@PERMANENT>...
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
Attaching centroids...
 100%
Reading band 1 of 1...
Link to raster map <dsm> created.
Reading areas...
 100%
Writing raster map...
 100%
All subsequent raster operations will be limited to the MASK area. Removing
or renaming raster map named 'MASK' will restore raster operations to
normal.
Column <height> not found in the table <polygon_points>. Creating...
Reading features from vector map...
Update vector attributes...
 100%
v.what.rast complete. 4 records updated.
Reading features from vector map ...
WARNING: Strip exists with insufficient data
Ignoring 1 points (too dense)
WARNING: 3 points given for interpolation (after thinning) is less than
         given NPMIN=300
WARNING: There are less than 600 points for interpolation. No segmentation
         is necessary, to run the program faster set segmax=600 (see
         manual)
Bitmap mask created
Processing segments in parallel...
Starting parallel work
 100%
v.surf.rst complete.
 100%
No clump map given, using MASK
 100%
1:0.01:5:710:576704.83:5188142.51:0.09
Execution of <sh script.sh> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
```

Note the last line: `1:0.01:5:710:576704.83:5188142.51:0.09`

### CODE REVIEW

**Comment by kikislater** [comment]
Error in proj is not cool in both cases ! 
Grass 7.8 move from proj 4 to proj 6 (and not relevant here but from python 2 to python 3, could it reduces or increases docker images ? )

What are the coordinates input of ${area_file} ?

**Comment by pierotofy** [comment]
EPSG:4326. `v.import` should reproject the coordinates to the workspace location if they don't match (and we set the location to the UTM zone of the elevation model at startup), so I'm thinking the problem might be elsewhere.

**Comment by pierotofy** [comment]
Attached is an example bundle (DSM, area_file, points_file and script) that works with GRASS 7.6 but does not in GRASS 7.8.

[test.zip](https://github.com/OpenDroneMap/WebODM/files/3652489/test.zip)

**Comment by kikislater** [comment]
I will explore it tomorrow

**Comment by kikislater** [comment]
Main problem is it's not reproject well when using v.import : 

```
GRASS 7.8.0 (test2):~ > v.info polygon_area
 +----------------------------------------------------------------------------+
 | Nom :            polygon_area                                              |
 | Jeu de cartes :  test                                                      |
 | Location:        test2                                                     |
 | Database:        /home/giscan/SIG/GEOBASE/GRASSDB                            |
 | Title:                                                                     |
 | Map scale:       1:1                                                       |
 | Name of creator: giscan                                                      |
 | Organization:                                                              |
 | Source date:     Mon Sep 30 09:30:32 2019                                  |
 | Timestamp (first layer): none                                              |
 |----------------------------------------------------------------------------|
 | Map format:      native                                                    |
 |----------------------------------------------------------------------------|
 |   Type of map: vecteur (level: 2)                                          |
 |                                                                            |
 |   Number of points:       0               Number of centroids:  1          |
 |   Number of lines:        0               Number of boundaries: 1          |
 |   Number of areas:        1               Number of islands:    1          |
 |                                                                            |
 |   Map is 3D:              Non                                              |
 |   Number of dblinks:      1                                                |
 |                                                                            |
 |   Projection: UTM (zone 15)                                                |
 |                                                                            |
 |               N: -26622862.8049029    S: -26622903.91763569                |
 |               E: 16250622.13928142    W: 16250554.82789858                 |
 |                                                                            |
 |   Digitization threshold: 0                                                |
 |   Commentaire:                                                             |
 |                                                                            |
 +----------------------------------------------------------------------------+
```
And raster 
```
GRASS 7.8.0 (test2):~ > r.info dsm
 +----------------------------------------------------------------------------+
 | Map:      dsm                            Date: Mon Sep 30 09:33:56 2019    |
 | Mapset:   test                           Login of Creator: giscan            |
 | Location: test2                                                            |
 | DataBase: /home/giscan/SIG/GEOBASE/GRASSDB                                   |
 | Title:                                                                     |
 | Timestamp: none                                                            |
 |----------------------------------------------------------------------------|
 |                                                                            |
 |   Type of Map:  GDAL-link            Number of Categories: 0               |
 |   Data Type:    FCELL                                                      |
 |   Rows:         683                                                        |
 |   Columns:      745                                                        |
 |   Total Cells:  508835                                                     |
 |        Projection: UTM (zone 15)                                           |
 |            N: 5188206.10063509    S: 5188118.66339192   Res: 0.12801939    |
 |            E: 576763.21184982    W: 576667.81358091   Res: 0.12805137      |
 |   Range of data:    min = 157.05  max = 164.85                             |
 |                                                                            |
 |   Data Source:                                                             |
 |    /home/kiki/test/dsm.tif band 1                                          |
 |                                                                            |
 |                                                                            |
 |   Data Description:                                                        |
 |    gnr par r.external                                                      |
 |                                                                            |
 |   Comments:                                                                |
 |    r.external --overwrite input="/home/giscan/test/dsm.tif" output="dsm"     |
 |                                                                            |
 +----------------------------------------------------------------------------+
```
Looks like a proj 6 problem : when I force epsg=4326 in v.import I still have problem

**Comment by kikislater** [comment]
Please note that the script compute volume in 1 meter resolution and not in dsm resolution ...

**Comment by kikislater** [comment]
> Considering the substantial changes in PROJ 6+, it might no longer be possible to do fully automated reprojection, instead users need in some cases select the appropriate reprojection method for their particular data: there can be several methods available to transform coordinates from one CRS to another CRS, users have to decide which one to use. Just as a warning that v.import might not work as expected with proj 6+ and gdal 3+ in future releases of GRASS GIS.

Source : https://trac.osgeo.org/grass/ticket/3869

**Comment by pierotofy** [comment]
Thanks for looking into this @kikislater :pray: 

For the volume resolution, do you have suggestions?

Is the takeaway that we should use `v.in.ogr` instead?

**Comment by kikislater** [comment]
And 7.6 is LTS so should be good to keep this version IMO.

Vector doesn't have resolution so it keeps 1 meter if you never set it. Most of the time meter resolution is sufficient in GIS world but you would suffer from people saying "well, ODM is not accurate and precise in computation!". 
Remember that if you set to lower computation it will add some more computation time : more cells, more time to compute.

What I will do is that : 

```
# Set region resolution to DSM to provide accurate measurement
g.region rast=dsm
# Set region to polygon area to calculate volume
g.region vect=polygon_area
```

**Pull request merged**
