### PR TITLE
refactor: Update Django to 4.2 LTS

### PR DESCRIPTION
**Pull request by NtskwK**
# What's new

## Docker-compose:

[Version top-level element (obsolete)](https://github.com/compose-spec/compose-spec/blob/main/04-version-and-name.md)

## Django 4.2:

[Django 4.2 supports PostgreSQL 12 and highe](https://docs.djangoproject.com/en/5.0/releases/4.2/#dropped-support-for-postgresql-11)

[django.conf.urls.url() is removed.](https://docs.djangoproject.com/en/4.1/releases/4.0/#features-removed-in-4-0)

[django.utils.encoding.force_text() and are removed.smart_text()](https://docs.djangoproject.com/en/4.2/releases/4.0/#:~:text=django.utils.encoding.force_text()%20and%20are%20removed.smart_text())

[PostgreSQL JSONField is deprecated](https://docs.djangoproject.com/en/5.1/releases/3.1/#postgresql-jsonfield)

## Others

PostGIS Support Matrix: https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS

### djangorestframework-simplejwt
there are also many different from [django-rest-framework-jwt](https://github.com/jpadilla/django-rest-framework-jwt) to [djangorestframework-simplejwt](https://github.com/jazzband/djangorestframework-simplejwt). So it can not pass the test in webodm.sh.

### rio-tiler

RioTilerBaseModel:warn 'key' access will has been deprecated and will be removed in rio-tiler 7.0."

### webpack

- (node:5096) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 
'map' is deprecated)

- (node:5096) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

- WARNING in webpack performance recommendations: webapp | You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.

### django-webpack-loader
There is a bug(?) in static template at v1.0.0 or higher version.

```
Error during template rendering In template /mnt/d/Program/gitwork/WebODM/app/templates/app/base.html
```

### Docker-compose

[Maintainer tag is deprecated](https://docs.docker.com/reference/build-checks/maintainer-deprecated/)

### CODE REVIEW

**Comment by NtskwK** [comment]
#1471

**Comment by pierotofy** [comment]
Thanks @NtskwK :wave: I haven't had a chance to review everything, but a few things stand out right away:

 * Please do not remove the database migrations! This would break updates from older versions.
 * It's nice to update Postgres to a newer version (ref #826), but I do not see a mechanism for performing a seamless update when users issue `./webodm.sh update`. This is a requirement for considering updating the database, and we are not going to break the installation for thousands of people. See this comment here https://github.com/OpenDroneMap/WebODM/issues/826#issuecomment-1275737159

**Comment by NtskwK** [comment]
Yes, an automated scripts souds good.
I see those files are not compatible here. It must be solved.
```
db\Dockerfile
...
> 83 | VOLUME /var/lib/postgresql/data
```
I have never tried to migrate database with data. Could you give me some suggest？

**Comment by NtskwK** [comment]
I found some manual about it. But I have no idea for it.

https://www.postgresql.org/docs/current/pgupgrade.html

**Pull request closed without merging**
