### PR TITLE
Record Movie with Potree

### PR DESCRIPTION
**Pull request by pierotofy**
Adds the ability to record animations directly from Potree (no need for screen recording software).

Also adds the ability to remove camera path animations.

### CODE REVIEW

**Comment by pierotofy** [comment]
Closes #1309

**Comment by pierotofy** [comment]
image

[recording (8).webm](https://github.com/OpenDroneMap/WebODM/assets/1951843/a7ed72cb-c7e9-42cf-835c-a464ca73ba5c)

**Comment by Saijin-Naib** [comment]
Sweet!

**Comment by smathermather** [comment]
woah! Missed this one. Very cool!

**Pull request merged**
