### PR TITLE
OpenAerialMap Plugin

### PR DESCRIPTION
**Pull request by pierotofy**
Do not merge yet, the work is not completed. This PR will add support for a plugin to push orthophotos directly to OpenAerialMap.

image

### CODE REVIEW

**Comment by smathermather** [comment]
w00t!

**Comment by pierotofy** [comment]
Takes care of #405 as well.

**Comment by pierotofy** [comment]
OAM Share Bridge repository: https://github.com/pierotofy/oam_share_bridge/

This is working. Will add unit tests for all the new additions to the plugin system, then this can be merged.

:clinking_glasses:

**Comment by smathermather** [comment]
:clinking_glasses: Cheers. :clinking_glasses:

**Comment by smathermather** [comment]
💥

**Comment by pierotofy** [comment]
Post announcement: https://www.opendronemap.org/2018/07/from-images-to-commons-fast-sharing-to-openaerialmap/

**Pull request merged**
