### PR TITLE
Rio update

### PR DESCRIPTION
**Pull request by markFieldman**
Reopen as merge to master. Thanks for the support!

### CODE REVIEW

**Comment by pierotofy** [comment]
Thanks for the PR! 

There's one more problem I've found: if you call the tile API without a `?rescale` parameter you get a crash:

```
http://localhost:8000/api/projects/1/tasks/80f0b969-ee13-412d-9c5d-5c917b4bcee3/orthophoto/tiles/21/512673/738967.png
```

You can reproduce this by taking the URL of a tile request and removing the `?rescale` parameter.

**Comment by markFieldman** [comment]
> Thanks for the PR!
> 
> There's one more problem I've found: if you call the tile API without a `?rescale` parameter you get a crash:
> 
> ```
> http://localhost:8000/api/projects/1/tasks/80f0b969-ee13-412d-9c5d-5c917b4bcee3/orthophoto/tiles/21/512673/738967.png
> ```
> 
> You can reproduce this by taking the URL of a tile request and removing the `?rescale` parameter.
> 
> ```
> AttributeError
> 'NoneType' object has no attribute 'split'
> /webodm/app/api/tiler.py in get, line 370
> ```
> 
> For orthophotos, there should be no rescaling if the rescale parameter is not passed.

Can we use default rescale like (0,256) in this case?

**Comment by pierotofy** [comment]
Good point, yes I set it to 0,255 https://github.com/OpenDroneMap/WebODM/pull/1067/commits/3d8d5a705f51ca1cfb158db255c9d742900b79bb by default

**Comment by pierotofy** [comment]
Looks good! I've made some small changes to avoid introducing matplotlib, but otherwise it's looking pretty solid.

Thanks so much for your contribution @markFieldman :pray: it looked like a fairly large effort.

**Comment by vincentsarago** [comment]
❤️ also FYI I'm actively working on rio-tiler V3 (after releasing new morecantile and rio-cogeo). Feel free to 👀 and 👋

**Comment by markFieldman** [comment]
> ❤️ also FYI I'm actively working on rio-tiler V3 (after releasing new morecantile and rio-cogeo). Feel free to 👀 and 👋

Thanks for your awesome product! Also thanks for you awesome documentation - it was so helpful! I filled very comfortable when works with rio-tiler 🙏

**Pull request merged**
