### PR TITLE
OSM quick editor plugin

### PR DESCRIPTION
**Pull request by pierotofy**
This plugin adds a button to quickly digitize a map from OpenStreetMap's ID editor:

image

image

@smathermather @dakotabenjamin this could help with a part of the FOSS4GNA workshop.

### CODE REVIEW

**Comment by pierotofy** [comment]
Updated the demo site, so this can be tried out: https://demo.webodm.org/map/project/3/task/b24f2131-05a7-4456-875f-e9c4fdb24378/

**Comment by smathermather** [comment]
This is 😎

**Comment by JamesLeonDufour** [comment]
Hi Piero, the link doesnt work in OSM even the project is shared;
http://34.69.208.110:8000/api/projects/1/tasks/8a95697a-5cc5-425d-abb3-f7db88368125/orthophoto/

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only, plus this is a pull request thread). Thank you! :+1:

**Pull request merged**
