### PR TITLE
Adds support for displaying cameras

### LINKED ISSUE #439: Show Cameras and Pictures
This is a feature that keeps being asked for. It would be cool to show where the camera shots are, with the ability to pull a thumbnail of the original image. Additionally it would be cool to show the coverage area for each camera.

### PR DESCRIPTION
**Pull request by pierotofy**
This PR aims to add support for displaying cameras.

image

Should close #439 #312

### CODE REVIEW

**Comment by smathermather** [comment]
Wo a a oah! Looking good.

**Comment by pierotofy** [comment]
Wait to see the 3D display :)

**Comment by pierotofy** [comment]
image

image

Cherry on top would be to display a preview of the images on the back of the camera screen, but I think I will leave that to a future PR....

**Comment by smathermather** [comment]
snail

**Comment by pierotofy** [comment]
Banana's got cameras too (with previews).

image

**Comment by pierotofy** [comment]
We're finally aligning the texture model view with the point cloud:

anim

**Comment by dmbworld** [comment]
Thanks @pierotofy, these are all great additions and improvements to WebODM. Just reprocessed some old tasks and taking advantage of them.

**Pull request merged**
