### PR TITLE
Making the search easier

### PR DESCRIPTION
**Pull request by italogrmn**
Makes searching easier by searching for substrings in project names. Previously, it only found if the search string was identical to the project name

### CODE REVIEW

**Comment by pierotofy** [comment]
Thanks for the PR @italogermano, however this would break search for task names within a project as well as removing the vector indexing (which is bad for performance).

**Comment by italogermano** [comment]
@pierotofy I got the result I expected before by exchanging:

        if len(names) > 0:
            project_name_vec = SearchVector("name")
            task_name_vec = SearchVector(StringAgg("task__name", delimiter=' '))
            name_query = SearchQuery(names, search_type="plain")
            qs = qs.annotate(n_search=project_name_vec + task_name_vec).filter(n_search=name_query
            
Per:

        if len(names) > 0:
            project_name_vec = SearchVector("name")
            task_name_vec = SearchVector(StringAgg("task__name", delimiter=' '))
            qs = qs.annotate(n_search=project_name_vec + task_name_vec).filter(n_search__icontains=names)

**Comment by pierotofy** [comment]
I understand that you're trying to make the search work for partial matches (e.g. have "te" match "test"). But I'm not sure this is what we want (even though I can see the use case).

The use of `__icontains` matches substrings, but has some shortcomings. For example:

Project name `test abc`: search query `abc test` --> no match
Project name `test`: search query `st` --> match. Arguably, a partial match could be helpful if it matched `te`, but not `st`?

https://docs.djangoproject.com/en/4.2/ref/contrib/postgres/search/

**Comment by italogermano** [comment]
If I understand, the problem should be solved with:

            name_query = SearchQuery(names, search_type="plain")
            qs = qs.annotate(n_search=project_name_vec + task_name_vec).filter(Q(n_search__icontains=names) | Q(n_search=name_query))

**Comment by pierotofy** [comment]
Almost; 

the take-away is: let's not use `icontains`. :pray:

**Pull request closed without merging**
