### PR TITLE
Display ground control points on map

### PR DESCRIPTION
**Pull request by pierotofy**
Display GCPs on map, including previews of images where the GCPs are tagged, with annotated/reprojection coordinates.﻿

### CODE REVIEW

**Comment by pierotofy** [comment]
Requires the changes in https://github.com/OpenDroneMap/ODM/pull/1351

**Comment by pierotofy** [comment]
image

image

Still need to add better zoom controls.

**Comment by pierotofy** [comment]
image

**Comment by pierotofy** [comment]
Translations now live on https://github.com/OpenDroneMap/WebODM-Locale

This will make it easier to sync with weblate automatically.

**Comment by mlopezantequera** [comment]
@pierotofy how are you guys annotating these points?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Pull request merged**
