### PR TITLE
Test task processing without orthophoto results, addition of availabl…

### LINKED ISSUE #90: Ability to download data even on failure
I would like to be able to download the point cloud or textured model even if the orthophoto fails, or anything really. Can we expose the "download all data" link even when it fails?

### PR DESCRIPTION
**Pull request by pierotofy**
Fixes #90 

@dakotabenjamin would you have some time to look over the changes sometimes :smile: ?

### CODE REVIEW

**Comment by smathermather** [comment]
w00t! This is nice.

screen shot 2017-03-14 at 7 47 01 pm

**Comment by smathermather** [comment]
One nice thing to add would be the ability to view the unreferenced point cloud and textured mesh if they are created.

**Comment by pierotofy** [comment]
Mm, yes that should be added. I'll see if I can get that added also.

**Comment by smathermather** [comment]
👍

**Comment by pierotofy** [comment]
I've added unreferenced point cloud and unreferenced 3d model display to WebODM. You'll be able to test these new changes once the docker image for node-opendronemap has finished building.

I'm pulling the unreferenced point cloud from opensfm/depthmaps/merged.ply, which does not have RGB information. Also if a user uses pmvs instead of opensfm, they are not going to get one.

If there's more interest in supporting better unreferenced point clouds (perhaps with RGB information included), this should be opened as a feature request in OpenDroneMap and generate the appropriate assets for WebODM to import them.

CC @dakotabenjamin

**Comment by pierotofy** [comment]
Will merge this by end of the day unless there are other suggestions :smile:

**Comment by smathermather** [comment]
+1 I haven't tested the new changes, and Dakota won't be back online until next week, but on the surface this looks great.

One thought -- surely there's a version of the point cloud that has the RGB being generated, but agree this is an upstream ODM issue.

**Comment by smathermather** [comment]
opensfm/depthmaps/merged.ply should have RGB that we can use in display, e.g. diffuse_red, diffuse_green, diffuse_blue:

```
more merged.ply 
ply
format ascii 1.0
element vertex 3214715
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar diffuse_red
property uchar diffuse_green
property uchar diffuse_blue
end_header
15.6303 152.1648 -108.5888 -0.011 0.718 0.696 167 166 134
15.9232 152.1242 -108.5425 -0.011 0.718 0.696 158 153 126
16.2159 152.0837 -108.4962 -0.011 0.718 0.696 149 141 117
16.5627 152.1081 -108.5703 -0.008 0.720 0.694 145 136 115
39.0841 150.6257 -107.9206 0.059 0.495 0.867 177 174 141
39.4381 150.6427 -107.9822 -0.030 0.586 0.810 191 188 154
39.7064 150.5911 -107.9140 -0.044 0.577 0.815 190 188 152
40.0154 150.5721 -107.9075 0.108 0.542 0.833 181 178 143
40.3354 150.5618 -107.9174 0.137 0.543 0.829 186 183 145
40.6179 150.5220 -107.8715 0.162 0.530 0.833 191 188 151
40.9960 150.5571 -107.9675 0.162 0.530 0.833 201 198 162
```

**Comment by pierotofy** [comment]
Uh, you are right. I'm doing a `pdal translate merged.ply output.las` prior to downloading the point cloud, perhaps that step is chopping away color information.

Need to investigate this and make a fix.

**Comment by pierotofy** [comment]
Problem is caused by the ply.reader filter in PDAL (well, it's not really a problem, more like an enforcement of standards), the mapping:

```
property uchar diffuse_red
property uchar diffuse_green
property uchar diffuse_blue
```

Is not recognized, but if I rename the properties to:

```
property uchar red
property uchar green
property uchar blue
```

Then things work fine. Maybe I could do a sed replacement prior to executing pdal.

**Comment by smathermather** [comment]
You can do the field mappings in PDAL, I think, using the ferry filter: https://www.pdal.io/stages/filters.ferry.html

**Comment by smathermather** [comment]
Come to think of it, is this true for all LAS files ODM produces? If so, open up an issue on ODM, as this should be fixed there.

**Comment by pierotofy** [comment]
Nop, the georefereced las file (odm_georeferenced_model.ply.las) of each project contains RGB info.

**Comment by pierotofy** [comment]
New changes in both WebODM and node-OpenDroneMap properly display RGB info in the point cloud now.

image

Command used for reference: pdal translate -i opensfm/depthmaps/merged.ply -o odm_georeferencing/odm_georeferenced_model.ply.las --json [{"dimensions":"diffuse_red = red, diffuse_green = green, diffuse_blue = blue","type":"filters.ferry"}]

https://github.com/OpenDroneMap/node-OpenDroneMap/commit/a0fa9661b4c6e9a9de5a5c64d8fa8db4128b1e03

**Pull request merged**
