### PR TITLE
New features and plugin in Webodm

### PR DESCRIPTION
**Pull request by emmadal**
I have bring new features and plugin on WebODM platform 

# Features

1. Move the sibebar menu on the top and add link in the navbar if the user authenticated is a super-admin

2. The content of all page take the full width

3. Possibility to add multiple user in the WebODM platform, that is to say when the platform started for the first times, there are not account. If a user created a first account he will be the only Administrator and the next account creation will be a standard user who can't access to the Admin panel

4. Add button (`Signup`, `Login`) to move on different page (```Welcome to Login```, and ```Login to Welcome```)

5. removing of unusable code in  `logged_in_base.html`

## Plugin

**add print plugin to print an 2D View Geotiff in PDF**

### CODE REVIEW

**Comment by pierotofy** [comment]
Hi @emmadal this looks great! There seems to be a conflict in `package.json` that needs to be resolved before we can review this?

**Comment by emmadal** [comment]
> Hi @emmadal this looks great! There seems to be a conflict in `package.json` that needs to be resolved before we can review this?

I have fix this issue in the `package.json` and i have commit for the merge

**Comment by pierotofy** [comment]
Thanks @emmadal ! It seems like the travis build failed, so this PR will need some checking before being merged. At a glance it looks good.

Have you thought about moving the print to PDF function as a plugin? (See https://github.com/OpenDroneMap/WebODM#manage-plugins).

**Comment by emmadal** [comment]
I recheck but it' the same the build failed. I will look yet to verify the merging

**Comment by pierotofy** [comment]
Finally had time to review this PR. A few notes that might need some additional changes before this can be merged:

1) If there are many items on a small screen, the menu bar items get clumped together:

image

Not sure what a good solution would be, perhaps grouping all plugin entries in a submenu?

2) Print to PDF could be moved to a plugin (like the `measure`, `contours` and `fullscreen` plugins). See https://github.com/OpenDroneMap/WebODM/tree/master/plugins/fullscreen

Would you have time to look over these @emmadal ?

**Comment by emmadal** [comment]
Yes i have the time now. I was busy in the last week. I will work on and to modify

**Comment by emmadal** [comment]
Thank you sir. I'm sorry I was too busy the last 2 weeks this is why I was missed to work on my PR. Today I'm available and I will see and fix the issues indicated by you. Thank you

**Comment by pierotofy** [comment]
No worries @emmadal ! Whenever you have time, there's no rush.

**Comment by pierotofy** [comment]
Any updates on this @emmadal ?

**Comment by emmadal** [comment]
sorry during the last month i was very busy on many projects. as soon (this April month) i will be free, i will can updates my PR @pierotofy 
Sorry @pierotofy

**Comment by pierotofy** [comment]
No worries, I was just checking!

**Comment by emmadal** [comment]
ok. i will upgrade my PR.
thanks

**Comment by pierotofy** [comment]
Closing this for now; please feel free to re-open once it's ready to be merged :pray:

**Pull request closed without merging**
