### PR TITLE
Updating README to reflect --db-data choice.

### PR DESCRIPTION
**Pull request by tariqislam**
Updating README to reflect --db-data choice.

### CODE REVIEW

**Comment by tariqislam** [comment]
@pierotofy @Saijin-Naib Small PR to update README to reflect the new command-line param.

**Review by Saijin-Naib — COMMENTED** [review]
Looks wonderful, but there is a repeated sentence fragment on L134. Could you fix that up?

**Comment by tariqislam** [comment]
Done @Saijin-Naib

**Comment by Saijin-Naib** [comment]
> Done @Saijin-Naib

I'm just waiting on CI, but I think this is fine to merge :)

**Comment by tariqislam** [comment]
Mind merging please? I have another PR coming :P

**Comment by pierotofy** [comment]
Thanks @tariqislam 🙏

**Comment by pierotofy** [comment]
Note that you can open multiple PRs while they are in review; you don't need to wait for a merge to start another one.

**Comment by tariqislam** [comment]
That's true, but in this specific case I just didn't want to confuse folks as one PR depended on the previous one to get merged.

**Pull request merged**
