### PR TITLE
Move task.console_output

### PR DESCRIPTION
**Pull request by pierotofy**
Following up on the work done around #1128, this PR moves the console output storage to the filesystem to avoid Postgres vacuuming issues (and improves overall performance, since we no longer need to constantly update table rows every few seconds).

### CODE REVIEW

**Comment by pierotofy** [comment]
FYI @OKaluza

**Comment by pierotofy** [comment]
@smathermather might also be happy about this for larger tasks. :)

**Comment by Saijin-Naib** [comment]
Oh, this is huge!

**Comment by smathermather** [comment]
Oh. Yeah. Woohoo!

**Pull request merged**
