### PR TITLE
Added django-guardian for row level permission

### PR DESCRIPTION
**Pull request by pierotofy**
Could you review these changes when you have a moment?

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
deleted webodm_webapp and webodm_db docker images and reran `docker-compose up`

```
Collecting django-knockout==0.3.2 (from -r requirements.txt (line 12))
  Could not find a version that satisfies the requirement django-knockout==0.3.2 (from -r requirements.txt (line 12)) (from versions: )
No matching distribution found for django-knockout==0.3.2 (from -r requirements.txt (line 12))
ERROR: Service 'webapp' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
dmb2@OpenDroneMap:~/WebODM$
```

**Comment by dakotabenjamin** [comment]
Do you mean any of these packages? https://pypi.python.org/pypi?%3Aaction=search&term=django+knockout&submit=search

**Comment by pierotofy** [comment]
The package is not available on pip (maybe I should take care of adding it myself for ease of use and for the benefit of the python community).

`pip install git+https://github.com/pierotofy/django-knockout`

Which is a fork of https://github.com/AntycSolutions/django-knockout

The command should be in the new Dockerfile.

**Comment by pierotofy** [comment]
Oh I see; I need to make an edit to Dockerfile to rearrange the order.

**Comment by pierotofy** [comment]
Should build properly now!

**Comment by dakotabenjamin** [comment]
Looks great so far. I was able to create a user and set permissions.

**Comment by pierotofy** [comment]
I accidentally merged this.

**Comment by dakotabenjamin** [comment]
I've spent more time with the app and haven't run into any critical issues. I got this traceback when I ran docker-compose again:
```
db        | STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$30000$0pmXR5hQEiHE$uyJgk6cG9p3aW2H29DkUpCGQRrPTZh3PCYv9x7QrTfg=', NULL, true, 'admin', '', '', 'admin@example.com', true, true, '2016-10-05T18:58:41.169737+00:00'::timestamptz) RETURNING "auth_user"."id"
webapp    | Traceback (most recent call last):
webapp    |   File "<console>", line 1, in <module>
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 168, in create_superuser
webapp    |     return self._create_user(username, email, password, **extra_fields)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 151, in _create_user
webapp    |     user.save(using=self._db)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 80, in save
webapp    |     super(AbstractBaseUser, self).save(*args, **kwargs)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
webapp    |     force_update=force_update, update_fields=update_fields)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
webapp    |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
webapp    |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
webapp    |     using=using, raw=raw)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
webapp    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1043, in _insert
webapp    |     return query.get_compiler(using=using).execute_sql(return_id)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
webapp    |     cursor.execute(sql, params)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
webapp    |     return super(CursorDebugWrapper, self).execute(sql, params)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
webapp    |     return self.cursor.execute(sql, params)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
webapp    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
webapp    |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
webapp    |     return self.cursor.execute(sql, params)
webapp    | IntegrityError: duplicate key value violates unique constraint "auth_user_username_key"
webapp    | DETAIL:  Key (username)=(admin) already exists.
```

So it looks like it's trying to recreate the admin user every time?

Otherwise in the permissions/groups page there's some text that can't be read in the text box:
webodm-perms

**Comment by pierotofy** [comment]
Yeah the errors are due to trying to recreate the default superuser (and failing). I guess that should be improved (I opened #27).

I opened also #28 for the CSS rules in the admin area.

Thanks for the feedback!

**Pull request merged**
