### PR TITLE
Localization and Translation

### PR DESCRIPTION
**Pull request by pierotofy**
Resuming work on the `i10n` branch that was started years ago.

Goal is to get localization and translation support in WebODM. Lots of stuff to do.

### CODE REVIEW

**Comment by smathermather** [comment]
Woah! Awesome.

**Comment by pierotofy** [comment]
Looks promising: 

image

**Comment by pierotofy** [comment]
Going to re-open a different PR so we can get the weblate efforts going right away.

**Comment by smathermather** [comment]
I might just default to _Italian_ because.

**Comment by pierotofy** [comment]
I was thinking of adding this to my default: https://www.technomancy.org/python/pirate-po-l10n-i18n-translate-your-site/

**Pull request closed without merging**
