### PR TITLE
Language of task.py reworked

### PR DESCRIPTION
**Pull request by comradekingu**
Should I pile on changes to other files here, or do a new PR for each?

### CODE REVIEW

**Review by pierotofy — APPROVED** [review]

**Comment by pierotofy** [comment]
Thanks @comradekingu :+1:

**Comment by pierotofy** [comment]
Could you base your PR from the `i10n2` branch however?

**Comment by comradekingu** [comment]
@pierotofy wIll do.

**Comment by comradekingu** [comment]
@pierotofy You aren't wrong. https://github.com/OpenDroneMap/ODM/pull/1160#issuecomment-694895089
I unsubscribed from translations for now, but I fixed the failing strings and the nb_NO resource. Somehow https://github.com/OpenDroneMap/documents/issues/2

**Pull request closed without merging**
