### PR TITLE
updated docker-compose files to v3

### PR DESCRIPTION
**Pull request by mostafaradwan**
- Updated docker-compose files to v3
- Added 3 replicas to the WebODM-webapp based on feedback from the American Redcross Team(ARC)
- This is part of a JIRA request from the code4good.io project at the ARC

### CODE REVIEW

**Comment by mostafaradwan** [comment]
Thanks for your attention @pierotofy.  That's a great point. 

Would it make sense to add it under a separate branch entitled (docker-compose-v3) and add a note in the README file?

**Comment by danbjoseph** [comment]
What if the v3 compose file is added but with a different file extension that keeps it from getting read by the docker commands, and the README notes that you'll need to switch the filenames to use the v3 file? 
Or would it be possible to adjust [webodm.sh](https://github.com/OpenDroneMap/WebODM/blob/master/webodm.sh) to use `docker-compose.yml` (v2) by default but accept a paramater that triggers the use of a `docker-compose.v3.yml`?

Regarding the "3 replicas" - our concern was just that the WebODM instance didn't seem to automatically restart after a system restart, and we were looking for either a code change or documentation to help us have WebODM come back up after the server itself was rebooted.

**Comment by pierotofy** [comment]
A separate branch would work also.

**Comment by danbjoseph** [comment]
A separate branch would require regular minor PRs to pull updates from the overall project over into the branch?
Does `replicas` even solve the issue of WebODM restarting after a system restart? From the [docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#replicas):
> If the service is replicated (which is the default), specify the number of containers that should be running at any given time.

How does running more containers help restart WebODM after a system restart?

**Comment by pierotofy** [comment]
> A separate branch would require regular minor PRs to pull updates from the overall project over into the branch?

Yes. So maybe not ideal. 

It would be interesting to hear more about the core issue that was being fixed/solved here. Maybe there are alternatives that don't require a migration to v3.

**Comment by danbjoseph** [comment]
It looks like the only big change with the upgraded docker-compose file is adding the following:
```
    deploy:
      mode: replicated
      replicas: 3
```
My concern was just that the WebODM instance didn't seem to automatically restart after a system restart, and I was looking for either a code change or documentation details to help us have WebODM come back up after the server itself was rebooted. It is unclear to me if `replicas` will solve the issue of WebODM restarting after a system restart. From the [docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#replicas): "If the service is replicated (which is the default), specify the number of containers that should be running at any given time." It is not clear to me how running more containers will help restart WebODM after a system restart.

**Comment by mostafaradwan** [comment]
@danbjoseph  Thanks for looking into this.

It's not clear to me what system restarts are. Is that the entire ODM stack? 

By having more replicas WebODM (the front-end component) should be more resilient and highly-available by having more than one container to handle requests in case one dies or restarts at any point.

The way to find out is to run a quick test, trigger a system restart, and observe if having 3 replicas resolves the issue.

Is that something you can try and report the results here?  Let me know if you've any questions.

**Comment by danbjoseph** [comment]
For example if using AWS and the EC2 instance is rebooted. Or local hardware running it such as an Intel NUC is turned off and back on.

**Comment by mostafaradwan** [comment]
@danbjoseph: I was under the impression this has to do with WebOEM container crashing sometimes and that's the point of adding the replicas. 

If you encounter rebooting issues of the underlying VMs (i.e: EC2 instances), the docker engine should restart as well and take care of recreating the containers. If Docker is not configured to start on boot, this is very easy to configure per the steps in the links below.

**Configure Docker to start on boot**
https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot

Please let me know your findings.

**Comment by pierotofy** [comment]
I'm going to close this PR for the time being, as this might be better solved by making infrastructure configuration changes rather than software changes. :pray:

**Pull request closed without merging**
